### ISSUE TITLE
ability to add link buttons to a message with a command 

### ISSUE THREAD

**Issue by 91DarioDev** [91DarioDev/forwardscoverbot#27]
The syntax should be like 

`/addbuttons text="{text}" link="link" && text="{text}" link="link" ...`

**Comment by jaindu** [comment]
I own a channel for movies & series.

But because of the copyright issues in telegram, I'm hoping to move everything in the channel to a new one.
but if I just forward everything to the new one they still could be removed. So as a solution to that I made a new bot using the this code
(Because then seems to be the bot has uploaded the contents)

What I need right now is, that when I forward my files to the bot, they should be posted directly on my new channel (bot is an admin on the channel)

**Comment by 91DarioDev** [comment]
You should change a bit the code so that instead of replying to you, the bot reply the message inside the channel. 

Honestly I don’t think telegram cares who uploaded the contests tho, they can still ban the channel
